### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by vnnimbalkar**

### CODE REVIEW

**Comment by atlantis-vm** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # google_storage_bucket.auto-expire will be destroyed
  # (because google_storage_bucket.auto-expire is not in configuration)
- resource "google_storage_bucket" "auto-expire" {
      - default_event_based_hold    = false -> null
      - effective_labels            = {} -> null
      - enable_object_retention     = false -> null
      - force_destroy               = true -> null
      - id                          = "no-public-access-bucketttt" -> null
      - labels                      = {} -> null
      - location                    = "US" -> null
      - name                        = "no-public-access-bucketttt" -> null
      - project                     = "upheld-rain-404605" -> null
      - public_access_prevention    = "enforced" -> null
      - requester_pays              = false -> null
      - rpo                         = "DEFAULT" -> null
      - self_link                   = "https://www.googleapis.com/storage/v1/b/no-public-access-bucketttt" -> null
      - storage_class               = "STANDARD" -> null
      - terraform_labels            = {} -> null
      - uniform_bucket_level_access = false -> null
      - url                         = "gs://no-public-access-bucketttt" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://35.223.70.45/lock?id=atlantis-vm%252Ftest-1%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by vnnimbalkar** [comment]
atlantis apply

**Comment by atlantis-vm** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Comment by vnnimbalkar** [comment]
everything is good

**Pull request merged**
