### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by vnnimbalkar**

### CODE REVIEW

**Comment by atlantis-vm** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
google_compute_instance.default: Refreshing state... [id=projects/upheld-rain-404605/zones/us-central1-a/instances/atlantis-vm]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # google_storage_bucket.auto-expire will be created
+ resource "google_storage_bucket" "auto-expire" {
      + effective_labels            = (known after apply)
      + force_destroy               = true
      + id                          = (known after apply)
      + location                    = "US"
      + name                        = "no-public-access-bucketttt"
      + project                     = (known after apply)
      + public_access_prevention    = "enforced"
      + rpo                         = (known after apply)
      + self_link                   = (known after apply)
      + storage_class               = "STANDARD"
      + terraform_labels            = (known after apply)
      + uniform_bucket_level_access = (known after apply)
      + url                         = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://35.223.70.45/lock?id=atlantis-vm%252Ftest-1%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by vnnimbalkar** [comment]
atlantis apply -d .

**Comment by atlantis-vm** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
google_storage_bucket.auto-expire: Creating...
google_storage_bucket.auto-expire: Creation complete after 1s [id=no-public-access-bucketttt]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by atlantis-vm** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
